name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Make sure you have a build script in your package.json

      - name: Set up Firebase CLI
        uses: firebase/github-actions@v1
        with:
          firebase_token: ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Ensure you have set this in GitHub Secrets
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}  # Ensure you have set this in GitHub Secrets

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting
